version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: foodstore-postgres
    environment:
      POSTGRES_DB: foodstore_db
      POSTGRES_USER: foodstore_user
      POSTGRES_PASSWORD: foodstore_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: